spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: wuliancan
     url: jdbc:mysql://127.0.0.1:3306/graphql?characterEncoding=UTF-8&useSSL=false
     schema: classpath:schema.sql
     initialization-mode: never
  jpa:
     show-sql: false
     hibernate:
       ddl-auto: update
#     properties:
#       hibernate:
#        enable_lazy_no_trans: true
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
  session:
    timeout: 86400

logging:
  level: info
  level.org.hibernate.type.descriptor.sql: trace
  level.org.hibernate.SQL: debug
server:
  port: 8082
  #level.org.hibernate.loader: debug


