spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: 123456
     url: jdbc:mysql://127.0.0.1:3306/graphql?characterEncoding=UTF-8&useSSL=false
     schema: classpath:schema.sql
     initialization-mode: never
  jpa:
     show-sql: true
     hibernate:
       ddl-auto: update
#     properties:
#       hibernate:
#        enable_lazy_no_trans: true
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379


logging:
  level: info
  level.org.hibernate.type.descriptor.sql: trace
  level.org.hibernate.SQL: debug
  #level.org.hibernate.loader: debug


